name: alradi_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.2
  enefty_icons: ^1.0.5
  eva_icons_flutter: ^3.1.0
  expandable: ^5.0.1
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_emoji: ^2.5.1
  flutter_form_builder: ^9.1.1
  salomon_bottom_bar: ^3.3.2
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Light.ttf