name: alradi_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.6+20

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.2
  enefty_icons: ^1.0.5
  eva_icons_flutter: ^3.1.0
  expandable: ^5.0.1
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_emoji: ^2.5.1
  flutter_form_builder: ^9.1.1
  flutter_pdfview: ^1.3.2
  intl: ^0.18.1
  salomon_bottom_bar: ^3.3.2
  url_launcher: ^6.1.14
  uuid: ^4.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - shorebird.yaml
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Light.ttf
