// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyweRVkfjpslU43ks5pkOFy_9Z6LU67os',
    appId: '1:91512150129:web:ce9d4aa0daccf8290523d0',
    messagingSenderId: '91512150129',
    projectId: 'alraed-club',
    authDomain: 'alraed-club.firebaseapp.com',
    storageBucket: 'alraed-club.appspot.com',
    measurementId: 'G-8R7TPTN81N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRT1Bqp9qtJcR1T4E3itnDX3ERlbW3ve0',
    appId: '1:91512150129:android:23d62e89cb86cf5d0523d0',
    messagingSenderId: '91512150129',
    projectId: 'alraed-club',
    storageBucket: 'alraed-club.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFHfapWip1VaE3duXitoNHiEDAA45546o',
    appId: '1:91512150129:ios:a3dd183ad715b54e0523d0',
    messagingSenderId: '91512150129',
    projectId: 'alraed-club',
    storageBucket: 'alraed-club.appspot.com',
    iosBundleId: 'com.alradiApp.mhmd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFHfapWip1VaE3duXitoNHiEDAA45546o',
    appId: '1:91512150129:ios:8ea396209de0e5ab0523d0',
    messagingSenderId: '91512150129',
    projectId: 'alraed-club',
    storageBucket: 'alraed-club.appspot.com',
    iosBundleId: 'com.alradiApp.mhmd.RunnerTests',
  );
}
